# Projek2 WUM
# e-shop clothing 2008
## Hubert Kozubek Arkadiusz Kniaź

In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# from sklearn.cluster import KMeans
import random

Data description “e-shop clothing 2008”

Variables:

1. YEAR (2008)

2. MONTH -> from April (4) to August (8)
3. DAY -> day number of the month

4. ORDER -> sequence of clicks during one session
5. COUNTRY -> variable indicating the country of origin of the IP address with the 
following categories:

1-Australia
2-Austria
3-Belgium
4-British Virgin Islands
5-Cayman Islands
6-Christmas Island
7-Croatia
8-Cyprus
9-Czech Republic
10-Denmark
11-Estonia
12-unidentified
13-Faroe Islands
14-Finland
15-France
16-Germany
17-Greece
18-Hungary
19-Iceland
20-India
21-Ireland
22-Italy
23-Latvia
24-Lithuania
25-Luxembourg
26-Mexico
27-Netherlands
28-Norway
29-Poland
30-Portugal
31-Romania
32-Russia
33-San Marino
34-Slovakia
35-Slovenia
36-Spain
37-Sweden
38-Switzerland
39-Ukraine
40-United Arab Emirates
41-United Kingdom
42-USA
43-biz (*.biz)
44-com (*.com)
45-int (*.int)
46-net (*.net)
47-org (*.org)
6. SESSION ID -> variable indicating session id (short record)


7. PAGE 1 (MAIN CATEGORY) -> concerns the main product category:
1-trousers
2-skirts
3-blouses
4-sale

========================================================

8. PAGE 2 (CLOTHING MODEL) -> contains information about the code for each product 
(217 products)

========================================================

9. COLOUR -> colour of product

1-beige
2-black
3-blue
4-brown
5-burgundy
6-gray
7-green
8-navy blue
9-of many colors
10-olive
11-pink
12-red
13-violet
14-white

========================================================

10. LOCATION -> photo location on the page, the screen has been divided into six parts:

1-top left
2-top in the middle
3-top right
4-bottom left
5-bottom in the middle
6-bottom right

========================================================

11. MODEL PHOTOGRAPHY -> variable with two categories: 

1-en face
2-profile

========================================================

12. PRICE -> price in US dollars

========================================================

13. PRICE 2 -> variable informing whether the price of a particular product is higher than 
the average price for the entire product category

1-yes
2-no

========================================================

14. PAGE -> page number within the e-store website (from 1 to 5)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++

If you use this dataset, please cite:

Łapczyński M., Białowąs S. (2013) Discovering Patterns of Users' Behaviour in an E-shop - 
Comparison of Consumer Buying Behaviours in Poland and Other European Countries, 
“Studia Ekonomiczne”, nr 151, “La société de l'information : perspective européenne et 
globale : les usages et les risques d'Internet pour les citoyens et les consommateurs”, p. 144-
153.


In [111]:
def progress_bar(iteration, total, prefix = '', suffix = '', decimals = 1, length = 100, fill = '█'):
    """
    Call in a loop to create terminal progress bar
    @params:
        iteration   - Required  : current iteration (Int)
        total       - Required  : total iterations (Int)
        prefix      - Optional  : prefix string (Str)
        suffix      - Optional  : suffix string (Str)
        decimals    - Optional  : positive number of decimals in percent complete (Int)
        length      - Optional  : character length of bar (Int)
        fill        - Optional  : bar fill character (Str)
    """
    percent = ("{0:." + str(decimals) + "f}").format(100 * (iteration / float(total)))
    filledLength = int(length * iteration // total)
    bar = fill * filledLength + '-' * (length - filledLength)
    print('\r%s |%s| %s%% %s' % (prefix, bar, percent, suffix), end = '\r')
    # Print New Line on Complete
    

In [23]:
df=pd.read_csv('e_shop_clothing_2008.csv',sep=';')
df

year  month  day  order  country  session ID  page 1 (main category)  \
0       2008      4    1      1       29           1                       1   
1       2008      4    1      2       29           1                       1   
2       2008      4    1      3       29           1                       2   
3       2008      4    1      4       29           1                       2   
4       2008      4    1      5       29           1                       2   
...      ...    ...  ...    ...      ...         ...                     ...   
165469  2008      8   13      1       29       24024                       2   
165470  2008      8   13      1        9       24025                       1   
165471  2008      8   13      1       34       24026                       1   
165472  2008      8   13      2       34       24026                       3   
165473  2008      8   13      3       34       24026                       2   

       page 2 (clothing model)  colour  location  model photography  price  \
0                          A13       1         5                  1     28   
1                          A16       1         6                  1     33   
2                           B4      10         2                  1     52   
3                          B17       6         6                  2     38   
4                           B8       4         3                  2     52   
...                        ...     ...       ...                ...    ...   
165469                     B10       2         4                  1     67   
165470                     A11       3         4                  1     62   
165471                      A2       3         1                  1     43   
165472                      C2      12         1                  1     43   
165473                      B2       3         1                  2     57   

        price 2  page  
0             2     1  
1             2     1  
2             1     1  
3             2     1  
4             1     1  
...         ...   ...  
165469        1     1  
165470        1     1  
165471        2     1  
165472        1     1  
165473        1     1  

[165474 rows x 14 columns]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165474 entries, 0 to 165473
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype 
---  ------                   --------------   ----- 
 0   year                     165474 non-null  int64 
 1   month                    165474 non-null  int64 
 2   day                      165474 non-null  int64 
 3   order                    165474 non-null  int64 
 4   country                  165474 non-null  int64 
 5   session ID               165474 non-null  int64 
 6   page 1 (main category)   165474 non-null  int64 
 7   page 2 (clothing model)  165474 non-null  object
 8   colour                   165474 non-null  int64 
 9   location                 165474 non-null  int64 
 10  model photography        165474 non-null  int64 
 11  price                    165474 non-null  int64 
 12  price 2                  165474 non-null  int64 
 13  page                     165474 non-null  int64 
dtypes: int64(13), object

In [25]:
df.columns

Index(['year', 'month', 'day', 'order', 'country', 'session ID',
       'page 1 (main category)', 'page 2 (clothing model)', 'colour',
       'location', 'model photography', 'price', 'price 2', 'page'],
      dtype='object')

In [26]:
# n_list = [2,3,4,5,6,7,8,9,10]

In [27]:
# inertia_list = []
# progress_bar(0, len(n_list), prefix = 'Progress:', suffix = 'Complete', length = 50)
# for index, n in enumerate(n_list):
#     model=KMeans(n_clusters=n)
#     label = model.fit_predict(df_new)
#     inertia_list.append(model.inertia_)
#     progress_bar(index+1, len(n_list), prefix = 'Progress:', suffix = 'Complete', length = 50)
# plt.plot(n_list, inertia_list, '-o')

In [28]:
# encoding categorical data
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
categorical_features = [feature for feature in df.columns if df[feature].dtypes == 'O']
for feature in categorical_features:
    df[feature]=label_encoder.fit_transform(df[feature])

In [29]:
for feature in categorical_features:
    print(feature, list(df[feature].unique()), list(label_encoder.fit_transform(df[feature].unique())), "\n")

page 2 (clothing model) [4, 7, 70, 51, 74, 127, 128, 198, 215, 66, 55, 58, 61, 1, 135, 162, 161, 109, 132, 77, 84, 209, 27, 30, 93, 89, 82, 124, 60, 2, 120, 191, 186, 185, 177, 180, 171, 150, 119, 57, 86, 103, 110, 121, 112, 9, 0, 43, 50, 22, 64, 65, 142, 11, 38, 35, 53, 47, 49, 75, 54, 59, 68, 69, 87, 102, 104, 126, 130, 192, 193, 39, 117, 67, 8, 40, 41, 42, 12, 25, 78, 90, 138, 33, 15, 46, 44, 81, 3, 24, 6, 73, 133, 85, 146, 136, 94, 100, 28, 29, 116, 156, 13, 194, 158, 160, 197, 187, 172, 168, 20, 62, 141, 10, 52, 48, 72, 21, 178, 98, 134, 105, 106, 108, 122, 123, 36, 63, 45, 190, 143, 137, 76, 80, 5, 16, 147, 169, 181, 152, 114, 115, 56, 23, 129, 125, 18, 26, 31, 32, 212, 145, 167, 213, 210, 208, 34, 71, 157, 201, 140, 144, 163, 131, 79, 99, 179, 202, 164, 216, 153, 182, 195, 165, 200, 14, 111, 139, 83, 175, 118, 214, 166, 176, 173, 189, 196, 107, 88, 95, 96, 113, 188, 148, 204, 205, 92, 170, 97, 203, 101, 91, 19, 206, 199, 207, 17, 154, 151, 37, 159, 183, 174, 184, 155, 149, 211] 

In [30]:
from pyclustering.cluster.kmedoids import kmedoids
from pyclustering.utils.metric import distance_metric, gower_distance_numpy
from pyclustering.cluster.center_initializer import random_center_initializer
from pyclustering.cluster.encoder import type_encoding
from pyclustering.cluster.encoder import cluster_encoder

In [31]:
X = df.iloc[:, :].values

## Defining Gower's distance

In [32]:
df.iloc[:,[3,11]].max() - df.iloc[:,[3,11]].min()

order    194
price     64
dtype: int64

In [33]:
import datetime as dt

In [34]:
def date_diff(d1, d2)-> int:
    delta = dt.date(2008, d2[0], d2[1]) - dt.date(2008, d1[0], d1[1])
    return abs(delta.days)

In [35]:
print(df.loc[df.iloc[:,1] == 4, 'day'].min())
print(df.loc[df.iloc[:,1] == 8, 'day'].max())

1
13


In [36]:
print(date_diff([4,1], [8,13]))

134


In [141]:
a = np.array([0,0,0,0])
b = np.array([0,1,2,3])
id = [0,2,3]
y = np.not_equal(a[id],b[id]).sum()
print(y)

2


In [160]:
from pyclustering.utils.metric import distance_metric, type_metric
import time
def my_gower(point1, point2):
    result = 0.0
    categorical = [4, 5, 6, 7, 8, 9, 10 , 12, 13] # categorical features
    start = time.time()
    result += np.not_equal(point1[categorical], point2[categorical]).sum()
    t1 = time.time() - start
    # print(result)
        
    numeric = [3, 11] # numeric features
    numeric_range = [194, 64] # range of numeric features

    start = time.time()
    result += (abs(point1[numeric] - point2[numeric])/numeric_range).sum()
    t2 = time.time() - start
    # print(result)

    date_columns = [1, 2] # month and day
    start = time.time()
    result += date_diff(point1[date_columns], point2[date_columns])/134 # Dates are from 1/04 to 13/08 so max is 134 days
    t3 = time.time() - start
    # print(result)
    return result/14, t1, t2, t3
# my_gower_metric = distance_metric(type_metric.USER_DEFINED, func=my_gower)


In [131]:
def calculate_gower_matrix(X):
    categorical = [4, 5, 6, 7, 8, 9, 10 , 12, 13] # categorical features
    numeric = [3, 11] # numeric features
    numeric_range = np.array([194, 64]) # range of numeric features
    date_columns = [1, 2] # month and day
    total = X.shape[0]

    col1 = np.reshape(np.repeat(X,X.shape[0], axis=0), [X.shape[0],X.shape[0],X.shape[1]])
    # print(col1)
    y = np.not_equal(X[:, categorical], col1[:, :, categorical]).sum(axis=2)
    t = (np.abs(col1[:,:,numeric] - X[:, numeric])/numeric_range).sum(axis=2)
    # matrix = [0]*total


    # for index, value in enumerate(X):
    #     row_cat = value[categorical]
    #     row_num = value[numeric]
    #     row_date = value[date_columns]
    #     matrix_row = [0]*total
    #     for i, val in enumerate(X):
    #         dist = 0.0
    #         # obs_cat = val[categorical]
    #         # obs_num = val[numeric]
    #         # obs_date = val[date_columns]
    #         dist += (row_cat != val[categorical]).sum()
    #         dist += (abs(row_num - val[numeric])/numeric_range).sum()
    #         dist += date_diff(row_date, val[date_columns])/134.0
    #         matrix_row[i] = dist
    #     progress_bar(index+1, total, prefix = 'Progress:', suffix = 'Complete', length = 50)
    #     matrix[index] = matrix_row
    return y+t

In [151]:
point1 = X[0]
point2 = X[50000]
date_columns = [1, 2]
delt = dt.date(2008, point1[date_columns[0]], point1[date_columns[1]]) - dt.date(2008, point2[date_columns[0]], point2[date_columns[1]])
# print(abs(delt.days))
# print(point1[date_columns])
distance = my_gower_metric(point1, point2)
# print(point1)
# print(point2)
# print(distance)

## Preparing K-means

In [42]:
from pyclustering.utils import calculate_distance_matrix 

In [128]:
X_test = np.array([[0,0,0],[1, 1, 1], [2, 2, 4], [0, 3, 4]])
col1 = np.reshape(np.repeat(X_test,X_test.shape[0], axis=0), [X_test.shape[0],X_test.shape[0],X_test.shape[1]])
# print(col1)
# y = np.not_equal(X_test[:, [0,1]], col1[:, :, [0,1]]).sum(axis=2)
b = [0,2]
range_mat = np.array([0.5,0.25])
t = (np.abs(col1[:,:,b] - X_test[:, b])/range_mat).sum(axis=2)
print(t)
# X_test.shape

[[ 0.  6. 20. 16.]
 [ 6.  0. 14. 14.]
 [20. 14.  0.  4.]
 [16. 14.  4.  0.]]


In [163]:
X_test = X[:1000]
progress_bar(0, X_test.shape[0], prefix = 'Progress:', suffix = 'Complete', length = 50)
total_time1 = 0
total_time2 = 0
total_time3 = 0
for i, val in enumerate(X_test):
    for ind, value in enumerate(X_test):
        _, t1, t2, t3 = my_gower(val, value)
        total_time1 += t1
        total_time2 += t2
        total_time3 += t3
    progress_bar(i+1, X_test.shape[0], prefix = 'Progress:', suffix = 'Complete', length = 50)
print("\n")
print("Time 1: ", total_time1)
print("Time 2: ", total_time2)
print("Time 3: ", total_time3)

Progress: |██████████████████████████████████████████████████| 100.0% Complete

Time 1:  13.738122463226318
Time 2:  12.474714517593384
Time 3:  7.402256488800049


In [158]:
initial_centers = random.sample(range(0, df.shape[0]), 10)
initial_centers = [0,1,2]
instanceKm = kmedoids(X[:1000],initial_index_medoids=initial_centers, metric=my_gower_metric)
instanceKm.process()

KeyboardInterrupt: 